Repository Maanna-zan/Maanna-zan_BE, pull requests merged in 2023-05, with the labels that each got.

#119 Feature/calendar
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Calendar.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Comment.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Kakao.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Likes.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Post.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Search.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Station.java
  src/main/java/com/hanghae99/maannazan/domain/file/S3Service.java
  src/main/java/com/hanghae99/maannazan/domain/find/FindService.java
  src/main/java/com/hanghae99/maannazan/domain/like/LikeService.java
  src/main/java/com/hanghae99/maannazan/global/exception/CustomErrorCode.java
  src/test/java/com/hanghae99/maannazan/domain/calendar/CalendarServiceTest.java
  src/test/java/com/hanghae99/maannazan/domain/file/S3ServiceTest.java
  src/test/java/com/hanghae99/maannazan/domain/post/PostServiceTest.java
Labels: feature

#120 fix : 배포주소 변경
  src/main/java/com/hanghae99/maannazan/global/config/CorsConfig.java
Labels: feature

#121 Dev
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/CalendarRequestDto.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Calendar.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Comment.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Kakao.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Likes.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Post.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Search.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Station.java
  src/main/java/com/hanghae99/maannazan/domain/file/S3Service.java
  src/main/java/com/hanghae99/maannazan/domain/find/FindService.java
  src/main/java/com/hanghae99/maannazan/domain/like/LikeService.java
  src/main/java/com/hanghae99/maannazan/global/config/CorsConfig.java
  src/main/java/com/hanghae99/maannazan/global/exception/CustomErrorCode.java
  src/test/java/com/hanghae99/maannazan/domain/calendar/CalendarServiceTest.java
  src/test/java/com/hanghae99/maannazan/domain/file/S3ServiceTest.java
  src/test/java/com/hanghae99/maannazan/domain/post/PostServiceTest.java
Labels: feature

#122 fix : CalendarServiceTest 성공케이스 테스트 완료
  src/test/java/com/hanghae99/maannazan/domain/calendar/CalendarServiceTest.java
Labels: feature

#123 Dev
  src/test/java/com/hanghae99/maannazan/domain/calendar/CalendarServiceTest.java
Labels: feature

#126 fix : PostResponseDto apiId, storename
  src/main/java/com/hanghae99/maannazan/domain/post/dto/PostRequestDto.java
  src/main/java/com/hanghae99/maannazan/domain/post/dto/PostResponseDto.java
  src/main/java/com/hanghae99/maannazan/domain/user/dto/CheckFindEmailRequestDto.java
  src/main/java/com/hanghae99/maannazan/domain/user/dto/CheckFindPwRequestDto.java
  src/test/java/com/hanghae99/maannazan/domain/user/UserServiceTest.java
Labels: bug

#143 Feature/map schedule
  .github/workflows/deploy.yml
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarController.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/MapRequestDto.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/MapResponseDto.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Schedule.java
  src/main/java/com/hanghae99/maannazan/domain/repository/ScheduleRepository.java
  src/main/java/com/hanghae99/maannazan/domain/user/UserService.java
  src/main/java/com/hanghae99/maannazan/global/exception/CustomErrorCode.java
Labels: feature

#144 Dev
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarController.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/MapRequestDto.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/MapResponseDto.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Schedule.java
  src/main/java/com/hanghae99/maannazan/domain/repository/ScheduleRepository.java
  src/main/java/com/hanghae99/maannazan/domain/user/UserService.java
  src/main/java/com/hanghae99/maannazan/global/exception/CustomErrorCode.java
Labels: feature

#147 Feature/map schedule
  src/main/java/com/hanghae99/maannazan/domain/post/PostService.java
  src/main/java/com/hanghae99/maannazan/domain/post/dto/PostResponseDto.java
Labels: bug

#148 Dev
  src/main/java/com/hanghae99/maannazan/domain/post/PostService.java
  src/main/java/com/hanghae99/maannazan/domain/post/dto/PostResponseDto.java
Labels: bug

#150 fix : 캘린더 메모 업데이트 기능, 삭제기능 수정 완료(인코딩되어 저장된 비밀번호가 문제였음))
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Calendar.java
  src/test/java/com/hanghae99/maannazan/domain/calendar/CalendarServiceTest.java
Labels: bug, feature

#151 Dev
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Calendar.java
  src/test/java/com/hanghae99/maannazan/domain/calendar/CalendarServiceTest.java
Labels: bug

#156 fix : 이메일 중복확인 기능 복구
  src/main/java/com/hanghae99/maannazan/domain/user/UserController.java
Labels: bug

#157 Dev
  src/main/java/com/hanghae99/maannazan/domain/user/UserController.java
Labels: bug

#158 fix : 이미지 업로드 실패 시 null값 반환하도록 수정 완료
  src/main/java/com/hanghae99/maannazan/domain/file/S3Service.java
Labels: bug

#159 Dev
  src/main/java/com/hanghae99/maannazan/domain/file/S3Service.java
Labels: bug

#162 Feature/map schedule
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/MapResponseDto.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Schedule.java
  src/main/java/com/hanghae99/maannazan/domain/post/PostService.java
  src/main/java/com/hanghae99/maannazan/domain/repository/PostRepository.java
  src/main/java/com/hanghae99/maannazan/global/exception/CustomErrorCode.java
Labels: feature

#163 Dev
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
  src/main/java/com/hanghae99/maannazan/domain/calendar/dto/MapResponseDto.java
  src/main/java/com/hanghae99/maannazan/domain/entity/Schedule.java
  src/main/java/com/hanghae99/maannazan/domain/post/PostService.java
  src/main/java/com/hanghae99/maannazan/domain/repository/PostRepository.java
  src/main/java/com/hanghae99/maannazan/global/exception/CustomErrorCode.java
Labels: feature

#164 fix : 일정 조회 시 날짜 값을 제대로 받지 않았던 에러 수정
  src/main/java/com/hanghae99/maannazan/domain/entity/Schedule.java
  src/main/java/com/hanghae99/maannazan/domain/user/UserService.java
Labels: feature

#165 Dev
  src/main/java/com/hanghae99/maannazan/domain/entity/Schedule.java
  src/main/java/com/hanghae99/maannazan/domain/user/UserService.java
Labels: bug

#166 fix : 캘린더 조회 시 조회되지 않는 에러 수정
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
Labels: bug

#167 Dev
  src/main/java/com/hanghae99/maannazan/domain/calendar/CalendarService.java
Labels: bug
